const EXPENSE_STATUS = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
});

const PAYMENT_METHOD = Object.freeze({
  CASH: "CASH",
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  UPI: "UPI",
  CHEQUE: "CHEQUE",
  WALLET: "WALLET",
  OTHER: "OTHER",
});

const BUDGET_PERIOD = Object.freeze({
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
});

const RECEIPT_PROCESSING_STATUS = Object.freeze({
  UPLOADED: "UPLOADED",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
});

const ALERT_TYPE = Object.freeze({
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  BUDGET_WARNING: "BUDGET_WARNING",
  UNUSUAL_SPENDING: "UNUSUAL_SPENDING",
  WEEKLY_REPORT: "WEEKLY_REPORT",
  MONTHLY_REPORT: "MONTHLY_REPORT",
  RECEIPT_PROCESSED: "RECEIPT_PROCESSED",
  EXPENSE_ADDED: "EXPENSE_ADDED",
});

const ALERT_SEVERITY = Object.freeze({
  INFO: "INFO",
  WARNING: "WARNING",
  ERROR: "ERROR",
  CRITICAL: "CRITICAL",
});

const REPORT_TYPE = Object.freeze({
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
  CUSTOM: "CUSTOM",
});

const REPORT_STATUS = Object.freeze({
  GENERATING: "GENERATING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
});
module.exports = {
  EXPENSE_STATUS,
  PAYMENT_METHOD,
  BUDGET_PERIOD,
  RECEIPT_PROCESSING_STATUS,
  ALERT_TYPE,
  ALERT_SEVERITY,
  REPORT_TYPE,
  REPORT_STATUS,
};
