const EXPENSE_STATUS = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
});

const PAYMENT_METHOD = Object.freeze({
  CASH: "CASH",
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  UPI: "UPI",
  CHEQUE: "CHEQUE",
  WALLET: "WALLET",
  OTHER: "OTHER",
});

const BUDGET_PERIOD = Object.freeze({
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
});

const REPORT_TYPE = Object.freeze({
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
  CUSTOM: "CUSTOM",
});

const REPORT_STATUS = Object.freeze({
  GENERATING: "GENERATING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
});
module.exports = {
  EXPENSE_STATUS,
  PAYMENT_METHOD,
  BUDGET_PERIOD,
  REPORT_TYPE,
  REPORT_STATUS,
};
